name: websocket
channels: !!python/tuple
- !!python/unicode
  'defaults'
dependencies:
- openssl=1.0.2f=0
- pip=9.0.1=py35_0
- python=3.5.2=0
- readline=6.2=2
- setuptools=27.2.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.2=0
- zlib=1.2.8=0
- pip:
  - autobahn==0.16.1
  - six==1.10.0
  - txaio==2.5.2

